### PR TITLE
Fixed some bug of txValidator

### PR DESCRIPTION
**Pull request by luodanwg**
1.implement of transaction asset precision check.
2.add transaction precision check when regtransaction.
3.when balance check add Value check and IssueAsset exception.
4.fixed a little bug of transactionResult's variable init problem.

Signed-off-by: luodanwg <luodan.wg@gmail.com>

### CODE REVIEW

**Comment by gasby88** [comment]
approve

**Comment by luodanwg** [comment]
fixed confilcs

**Comment by luodanwg** [comment]
fixed conflicts..

**Comment by luodanwg** [comment]
fixed conflicts again.

**Comment by luodanwg** [comment]
fixed conflicts again.

**Comment by luodanwg** [comment]
fixed conflicts.

**Pull request merged**
