### PR TITLE
Fix double spent issue in transaction pool

### PR DESCRIPTION
**Pull request by zhouziyan**
Removed duplicated inputs from UTXO Inputs List of transaction pool
when remove double spent transaction, which will cause double spend
when any transactions still refer to the inputs removed before.

Signed-off-by: Ziyan Zhou <zhouziyan@hotmail.com>

### CODE REVIEW

**Comment by laizy** [comment]
need more discussion

**Comment by zhouziyan** [comment]
@laizy The node will not broadcast full block(only block hash), so the transactions in pool will not come from block received. The conflicted transactions will not be added to transaction pool, the transaction pool only holds the first transaction which no duplicated inputs detected.

**Comment by laizy** [comment]
@zhouziyan , in consensus module, execution path: `PrepareRequestReceived -> ds.VerifyTxs ->  ds.localNet.AppendTxnPool(t) --> verifyTransactionWithTxnPool` . If hold the first transaction,  the consensus will not make progress.

**Comment by zhouziyan** [comment]
@laizy I don't think so, If the node receives un-verified transactions from other node, just throw it into local transaction pool do verification. It will  not impact consensus.

**Comment by laizy** [comment]
@zhouziyan ，

>  just throw it into local transaction pool do verification

yes，this is what  `ds.localNet.AppendTxnPool(t)`  did. Now the transaction has conflict transactions. in your opinion, the verification will not pass. And the node will not sign and relay its signature-->  impact consensus.

**Comment by zhouziyan** [comment]
@laizy As we talk about this question offline, this PR fixed a double spent bug.  Issue of Evil Primary Node will be fixed in next PR. Thanks for reviewing.

**Pull request closed without merging**
